### PR TITLE
feature(common):adding ticke-0006-last documents

### PR DESCRIPTION
**Pull request by yorca21**
please, engineer check my pr, it is the ticker-0006 that shows the last documents

### CODE REVIEW

**Review by Ditmar — APPROVED** [review]
nice pr

**Comment by Ditmar** [comment]
Please fix the conflicts

**Comment by yorca21** [comment]
Conflicts resolved, please, engineer, review the p

**Comment by yorca21** [comment]
git rebase




engineer, already made the rebase, please verify it

**Comment by yorca21** [comment]
engineer, already made the rebase, please verify it

**Pull request merged**
